name = "vfsgnjx.vf"
format = "vd,vs2,fs1,vm"

[tests]
fsew16 = [
    [ "1.0",  "1.0"],
    [ "1.0", "-1.0"],
    [ "1.0", "-0.0"],
    [ "1.0",  "0.0"],
    ["-1.0", "-0.0"],
    ["-1.0",  "0.0"],
    ["-0.0",  "0.0"],
    [ "0.0", "-0.0"],
    ["-3.14159265",  "0.0001"],
    ["-3.14159265", "-0.0001"]
]
fsew32 = [
    [ "1.0",  "1.0"],
    [ "1.0", "-1.0"],
    [ "1.0", "-0.0"],
    [ "1.0",  "0.0"],
    ["-1.0", "-0.0"],
    ["-1.0",  "0.0"],
    ["-0.0",  "0.0"],
    [ "0.0", "-0.0"],
    ["-3.14159265",  "0.0001"],
    ["-3.14159265", "-0.0001"]
]
fsew64 = [
    [ "1.0",  "1.0"],
    [ "1.0", "-1.0"],
    [ "1.0", "-0.0"],
    [ "1.0",  "0.0"],
    ["-1.0", "-0.0"],
    ["-1.0",  "0.0"],
    ["-0.0",  "0.0"],
    [ "0.0", "-0.0"],
    ["-3.14159265",  "0.0001"],
    ["-3.14159265", "-0.0001"]
]
