name = "vrev8.v"
fp = false
format = "vd,vs2,vm"

[tests]
base = [
    [0x0],
    [0x1],
    [0x2],
    [0x3],
    [0xf]
]
sew8 = [
    [0x00],
    [0xf8],
    [0x08],
    [0x7f],
    [0x07],
    [0x01],
    [0xff]
]
sew16 = [
    [0x0000],
    [0xfff8],
    [0xff80],
    [0x7fff],
    [0x07ff],
    [0x0001],
    [0xffff]
]
sew32 = [
    [0x00000000],
    [0xfffffff8],
    [0x7fffff80],
    [0x00007fff],
    [0x000007ff],
    [0x00000001],
    [0xffffffff]
]
sew64 = [
    ["0x0000000000000000"],
    ["0xffffffffffff8000"],
    ["0xffffffff80000000"],
    ["0x0000000000007fff"],
    ["0x000000007fffffff"],
    ["0x0000000000000001"],
    ["0xffffffffffffffff"]
]
