name = "vsseg4e64.v"
fp = false
format = "vs3,(rs1),vm"

[tests]
base = [
    [0x0],
    [0x1],
    [0x2],
    [0xf]
]
sew64 = [
    ["0x7fffffffffffffff"],
    ["0xfffffffffffffff8"],
    ["0xffffffffffffffff"]
]
